# Generated by Django 2.0.7 on 2018-12-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('email', models.EmailField(blank=True, help_text='e.g. Student Email', max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='e.g. John Smith', max_length=60)),
                ('phone', models.CharField(blank=True, help_text='e.g. 555-555-5555', max_length=10)),
                ('school', models.CharField(blank=True, help_text='e.g. UMass Amherst', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('poc', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(blank=True, help_text='e.g. BS Computer Science', max_length=100)),
                ('major2', models.CharField(blank=True, help_text='e.g. BA Math ', max_length=100)),
                ('gradyear', models.DateField(blank=True, null=True)),
                ('fisrtgen', models.BooleanField(default=False)),
                ('degree', models.CharField(blank=True, help_text='e.g. MS Art ', max_length=100)),
                ('job', models.CharField(blank=True, help_text='e.g. Tutor at Umass ', max_length=100)),
                ('endofyear', models.DateField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='e.g. Party', max_length=60)),
                ('site', models.CharField(blank=True, help_text='e.g. Caffeteria', max_length=60)),
                ('date', models.DateField(blank=True, null=True)),
                ('tour', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('email', models.EmailField(blank=True, help_text='e.g. Student Email', max_length=70, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges.Event')),
            ],
        ),
        migrations.CreateModel(
            name='HSStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegechoice', models.CharField(blank=True, help_text='e.g. UMass, Ucon', max_length=100)),
                ('pemail', models.EmailField(blank=True, help_text='e.g. Parent Email', max_length=70)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g. Volenteer', max_length=60)),
                ('date', models.DateField(blank=True, null=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges.Affiliate')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='e.g. John Smith', max_length=60)),
                ('email', models.EmailField(blank=True, help_text='e.g. Student Email', max_length=70)),
                ('phone', models.CharField(blank=True, help_text='e.g. 555-555-5555', max_length=10)),
                ('year', models.IntegerField(blank=True, default=2018, help_text='e.g. 2020')),
                ('pronoun', models.CharField(blank=True, help_text='e.g Him/his/he', max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('color', models.BooleanField(default=False)),
                ('firstgen', models.BooleanField(default=False)),
                ('workstudy', models.BooleanField(default=False)),
                ('major', models.CharField(blank=True, help_text='e.g. Comp Sci', max_length=50)),
            ],
        ),
    ]
