# Generated by Django 2.1.1 on 2018-12-11 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='e.g. Party', max_length=60)),
                ('site', models.CharField(blank=True, help_text='e.g. Caffeteria', max_length=60)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('email', models.EmailField(blank=True, help_text='e.g. Student Email', max_length=70, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bridges.Event')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('email', models.EmailField(blank=True, help_text='e.g. Student Email', max_length=70, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='e.g. John Smith', max_length=60)),
                ('phone', models.CharField(blank=True, help_text='e.g. 555-555-5555', max_length=10)),
                ('school', models.CharField(blank=True, help_text='e.g. UMass Amherst', max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('major', models.CharField(blank=True, help_text='e.g. BS Computer Science', max_length=100)),
                ('poc', models.CharField(blank=True, help_text='e.g. Yes/No', max_length=50)),
                ('gender', models.CharField(blank=True, help_text='e.g. John Smith', max_length=60)),
                ('role', models.CharField(blank=True, help_text='e.g. Tutor, Student, Teacher', max_length=100)),
                ('fisrtgen', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g. Volenteer', max_length=60)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
