# Generated by Django 2.1.1 on 2018-12-18 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='email',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='id',
            field=models.AutoField(auto_created=True, default=19900909, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='event',
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ManyToManyField(blank=True, to='bridges.Event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='people',
            field=models.ManyToManyField(blank=True, to='bridges.Profile'),
        ),
    ]
