# Generated by Django 2.0.7 on 2018-10-18 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='year',
            field=models.CharField(blank=True, help_text='What school year', max_length=200, null=True),
        ),
    ]
