# Generated by Django 2.0 on 2018-12-04 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Sale Summary',
                'verbose_name_plural': 'Sales Summary',
                'proxy': True,
                'indexes': [],
            },
            bases=('bridges.survey',),
        ),
        migrations.AddField(
            model_name='survey',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Date'),
        ),
    ]
