# Generated by Django 2.1.1 on 2018-12-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bridges', '0003_auto_20181218_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventattendee',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventattendee',
            name='people',
        ),
        migrations.AddField(
            model_name='profile',
            name='firstgen',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, help_text='e.g. John Smith', max_length=60),
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.CharField(blank=True, help_text='e.g. Tutor, Student, Teacher', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(blank=True, help_text='e.g. BS Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='e.g. 555-555-5555', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='poc',
            field=models.CharField(blank=True, help_text='e.g. Yes/No', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, help_text='e.g. UMass Amherst', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, default=2018, help_text='e.g. 2020'),
        ),
        migrations.DeleteModel(
            name='EventAttendee',
        ),
    ]
